simplify to test ordering

diff --git a/.github/workflows/copilot_deploy.yml b/.github/workflows/copilot_deploy.yml
--- a/.github/workflows/copilot_deploy.yml
+++ b/.github/workflows/copilot_deploy.yml
@@ -65,48 +65,42 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v2
 
-      - name: "Set version in env"
-        id: set-version
-        run: |
-          source version
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+      # - name: Docker metadata
+      #   id: metadata
+      #   uses: docker/metadata-action@v4
+      #   with:
+      #     images: ${{env.IMAGE_REPO_PATH}}/${{env.IMAGE_NAME}}
+      #     tags: |
+      #       type=sha,format=long
+      #       type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
+      #       type=raw,value=${{env.VERSION}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
+      #       type=ref,event=branch
 
-      - name: Docker metadata
-        id: metadata
-        uses: docker/metadata-action@v4
-        with:
-          images: ${{env.IMAGE_REPO_PATH}}/${{env.IMAGE_NAME}}
-          tags: |
-            type=sha,format=long
-            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
-            type=raw,value=${{env.VERSION}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
-            type=ref,event=branch
+      # - name: Log in to the Container registry
+      #   uses: docker/login-action@v1
+      #   with:
+      #     registry: ${{ env.DOCKER_REGISTRY }}
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Log in to the Container registry
-        uses: docker/login-action@v1
-        with:
-          registry: ${{ env.DOCKER_REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Create .env for runner workspace
+      #   run: |
+      #     touch ./runner/.env
+      #     echo LAST_TAG_GH=runner >> ./runner/.env
+      #     echo LAST_COMMIT_GH=runner >> ./runner/.env
+      #     cat ./runner/.env
 
-      - name: Create .env for runner workspace
-        run: |
-          touch ./runner/.env
-          echo LAST_TAG_GH=runner >> ./runner/.env
-          echo LAST_COMMIT_GH=runner >> ./runner/.env
-          cat ./runner/.env
-
-      - name: Build and push docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          tags: ${{ steps.metadata.outputs.tags}}
-          labels: ${{ steps.metadata.outputs.labels }}
-          push: true
-          file: ./fsd_config/Dockerfile
-          build-args: |
-            LAST_TAG='${{env.VERSION}}'
-            LAST_COMMIT='${{ github.sha }}'
+      # - name: Build and push docker image
+      #   uses: docker/build-push-action@v4
+      #   with:
+      #     context: .
+      #     tags: ${{ steps.metadata.outputs.tags}}
+      #     labels: ${{ steps.metadata.outputs.labels }}
+      #     push: true
+      #     file: ./fsd_config/Dockerfile
+      #     build-args: |
+      #       LAST_TAG='${{env.VERSION}}'
+      #       LAST_COMMIT='${{ github.sha }}'
 
   dev_deploy:
     permissions:
@@ -114,27 +108,35 @@ jobs:
       contents: read # This is required for actions/checkout
     needs: [docker-build, setup]
     if: ${{ always() && contains(fromJSON(needs.setup.outputs.jobs_to_run), 'dev') && (! contains(needs.*.result, 'failure') ) && (! contains(needs.*.result, 'cancelled') ) }}
-    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@main
-    secrets:
-      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
-    with:
-      environment: dev
-      app_name: "form-runner"
-      version: sha-${{ github.sha }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+    # uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@main
+    # secrets:
+    #   AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
+    # with:
+    #   environment: dev
+    #   app_name: "form-runner"
+    #   version: sha-${{ github.sha }}
 
   post_dev_deploy_tests:
     needs: [dev_deploy]
-    secrets:
-      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
-      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
-    uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
-    with:
-      run_performance_tests: ${{ inputs.run_performance_tests || true }}
-      run_e2e_tests: ${{ inputs.run_e2e_tests }}
-      run_static_security_python: false
-      run_zap_scan: false
-      app_name: forms
-      environment: dev
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+    # secrets:
+    #   FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
+    #   FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
+    # uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
+    # with:
+    #   run_performance_tests: ${{ inputs.run_performance_tests || true }}
+    #   run_e2e_tests: ${{ inputs.run_e2e_tests }}
+    #   run_static_security_python: false
+    #   run_zap_scan: true
+    #   app_name: forms
+    #   environment: dev
 
   test_deploy:
     permissions:
@@ -142,27 +144,35 @@ jobs:
       contents: read # This is required for actions/checkout
     needs: [setup, docker-build, dev_deploy, post_dev_deploy_tests]
     if: ${{ always() && contains(fromJSON(needs.setup.outputs.jobs_to_run), 'test') && (! contains(needs.*.result, 'failure') ) && (! contains(needs.*.result, 'cancelled') ) }}
-    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@main
-    secrets:
-      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
-    with:
-      environment: "test"
-      app_name: "form-runner"
-      version: sha-${{ github.sha }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+    # uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@main
+    # secrets:
+    #   AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
+    # with:
+    #   environment: "test"
+    #   app_name: "form-runner"
+    #   version: sha-${{ github.sha }}
 
   post_test_deploy_tests:
     needs: test_deploy
-    secrets:
-      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
-      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
-    uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
-    with:
-      run_performance_tests: ${{ inputs.run_performance_tests || true }}
-      run_e2e_tests: ${{ inputs.run_e2e_tests }}
-      run_static_security_python: false
-      run_zap_scan: false
-      app_name: forms
-      environment: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+    # secrets:
+    #   FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
+    #   FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
+    # uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
+    # with:
+    #   run_performance_tests: ${{ inputs.run_performance_tests || true }}
+    #   run_e2e_tests: ${{ inputs.run_e2e_tests }}
+    #   run_static_security_python: false
+    #   run_zap_scan: true
+    #   app_name: forms
+    #   environment: test
 
   uat_deploy:
     permissions:
@@ -178,47 +188,55 @@ jobs:
         post_test_deploy_tests,
       ]
     if: ${{ always() && contains(fromJSON(needs.setup.outputs.jobs_to_run), 'uat') && (! contains(needs.*.result, 'failure') ) && (! contains(needs.*.result, 'cancelled') ) }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
     uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@main
-    secrets:
-      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
-    with:
-      environment: "uat"
-      app_name: "form-runner"
-      version: sha-${{ github.sha }}
+    # secrets:
+    #   AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
+    # with:
+    #   environment: "uat"
+    #   app_name: "form-runner"
+    #   version: sha-${{ github.sha }}
 
   post_uat_deploy_tests:
     needs: uat_deploy
-    secrets:
-      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
-      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
-    uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
-    with:
-      run_performance_tests: ${{ inputs.run_performance_tests || true }}
-      run_e2e_tests: ${{ inputs.run_e2e_tests  }}
-      run_static_security_python: false
-      run_zap_scan: false
-      app_name: forms
-      environment: uat
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+    # secrets:
+    #   FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
+    #   FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
+    # uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
+    # with:
+    #   run_performance_tests: ${{ inputs.run_performance_tests || true }}
+    #   run_e2e_tests: ${{ inputs.run_e2e_tests  }}
+    #   run_static_security_python: false
+    #   run_zap_scan: true
+    #   app_name: forms
+    #   environment: uat
 
-  prod_deploy:
-    permissions:
-      id-token: write # This is required for requesting the JWT
-      contents: read # This is required for actions/checkout
-    needs:
-      [
-        setup,
-        docker-build,
-        dev_deploy,
-        post_dev_deploy_tests,
-        test_deploy,
-        post_test_deploy_tests,
-        post_uat_deploy_tests,
-      ]
-    if: ${{ always() && contains(fromJSON(needs.setup.outputs.jobs_to_run), 'prod') && (! contains(needs.*.result, 'failure') ) && (! contains(needs.*.result, 'cancelled') ) }}
-    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@main
-    secrets:
-      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
-    with:
-      environment: "prod"
-      app_name: "form-runner"
-      version: sha-${{ github.sha }}
+  # prod_deploy:
+  #   permissions:
+  #     id-token: write # This is required for requesting the JWT
+  #     contents: read # This is required for actions/checkout
+  #   needs:
+  #     [
+  #       setup,
+  #       docker-build,
+  #       dev_deploy,
+  #       post_dev_deploy_tests,
+  #       test_deploy,
+  #       post_test_deploy_tests,
+  #       post_uat_deploy_tests,
+  #     ]
+  #   if: ${{ always() && contains(fromJSON(needs.setup.outputs.jobs_to_run), 'prod') && (! contains(needs.*.result, 'failure') ) && (! contains(needs.*.result, 'cancelled') ) }}
+  #   uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@main
+  #   secrets:
+  #     AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
+  #   with:
+  #     environment: "prod"
+  #     app_name: "form-runner"
+  #     version: sha-${{ github.sha }}
